// src/content/educationData.js
// Education and certification data for the resume.
// Updated: 2025-12-01

export const EDUCATION = [
  {
    id: "bba-umss",
    degree: "Bachelor in Business Administration",
    school: "UMSS · Cochabamba, Bolivia",
    year: "2001",
    logoSrc: "/logos/umss.png",
    institutionUrl: "https://www.umss.edu.bo/",
  },
  {
    id: "human-systems-integration-gatech",
    degree: "Certificate in Human Systems Integration",
    school: "Georgia Tech",
    year: "2018",
    logoSrc: "/logos/georgia-tech.png",
    institutionUrl: "https://www.gatech.edu/",
  },
];

// Add category fields to CERTIFICATIONS inside educationData.js
export const CERTIFICATIONS = [
  {
    id: "ai-foundational-booz-allen",
    title: "Artificial Intelligence Foundational",
    issuer: "Booz Allen",
    year: "2024",
    logoSrc: "/logos/booz-allen.png",
    verifyUrl:
      "https://www.credly.com/org/booz-allen-hamilton/badge/artificial-intelligence-foundational",
    institutionUrl: "https://www.boozallen.com/",
    category: "AI",
  },
  {
    id: "ai-enablement-booz-allen",
    title: "Artificial Intelligence, Enablement",
    issuer: "Booz Allen",
    year: "2024",
    logoSrc: "/logos/booz-allen.png",
    verifyUrl:
      "https://www.credly.com/org/booz-allen-hamilton/badge/artificial-intelligence-enablement",
    institutionUrl: "https://www.boozallen.com/",
    category: "AI",
  },
  {
    id: "cua-hfi",
    title: "Certified Usability Analyst",
    issuer: "Human Factors International",
    year: "2018",
    logoSrc: "/logos/hfi.png",
    institutionUrl: "https://humanfactors.com/",
    category: "UX",
  },
  {
    id: "ux-master-certification-nng",
    title: "UX Master Certification",
    issuer: "Nielsen Norman Group",
    year: "2021",
    logoSrc: "/logos/nng.png",
    verifyUrl: "https://www.credly.com/badges/verification-placeholder-nng-ux-master",
    institutionUrl: "https://www.nngroup.com/",
    category: "UX",
  },
  {
    id: "ux-management-nng",
    title: "UX Management",
    issuer: "Nielsen Norman Group",
    year: "2021",
    logoSrc: "/logos/nng.png",
    verifyUrl: "https://www.credly.com/badges/verification-placeholder-nng-ux-management",
    institutionUrl: "https://www.nngroup.com/",
    category: "UX",
  },
  {
    id: "interaction-design-nng",
    title: "Interaction Design",
    issuer: "Nielsen Norman Group",
    year: "2020",
    logoSrc: "/logos/nng.png",
    verifyUrl: "https://www.credly.com/badges/verification-placeholder-nng-interaction",
    institutionUrl: "https://www.nngroup.com/",
    category: "UX",
  },

  {
    id: "ux-research-nng",
    title: "UX Research & ResearchOps",
    issuer: "Nielsen Norman Group",
    year: "2020",
    logoSrc: "/logos/nng.png",
    verifyUrl: "https://www.credly.com/badges/verification-placeholder-nng-ux-research",
    institutionUrl: "https://www.nngroup.com/",
    category: "UX",
  },
  {
    id: "trusted-tester-dhs",
    title: "Trusted Tester",
    issuer: "Customer Experience Directorate (DHS)",
    year: "2023",
    logoSrc: "/logos/trusted-tester-dhs.png",
    verifyUrl: "https://www.dhs.gov/trusted-tester/certifications/verification-placeholder",
    institutionUrl: "https://www.dhs.gov/trusted-tester",
    category: "Accessibility",
  },
  {
    id: "csm-scrum-alliance",
    title: "Certified Scrum Master",
    issuer: "Scrum Alliance",
    year: "2019",
    logoSrc: "/logos/scrum-alliance.png",
    verifyUrl: "https://bcert.me/verification-placeholder-scrum-alliance",
    institutionUrl: "https://www.scrumalliance.org/",
    category: "Agile",
  },
  {
    id: "icp-agile-professional",
    title: "Certified Agile Professional",
    issuer: "ICAgile",
    year: "2020",
    logoSrc: "/logos/ic-agile.png",
    institutionUrl: "https://www.icagile.com/",
    category: "Agile",
  },
  {
    id: "icp-atf-team-facilitator",
    title: "Certified Team Facilitator",
    issuer: "ICAgile",
    year: "2021",
    logoSrc: "/logos/ic-agile.png",
    verifyUrl: "https://www.icagile.com/verification-placeholder-atf",
    institutionUrl: "https://www.icagile.com/",
    category: "Agile",
  },
  {
    id: "icp-acc-team-coach",
    title: "Certified Team Coach",
    issuer: "ICAgile",
    year: "2022",
    logoSrc: "/logos/ic-agile.png",
    verifyUrl: "https://www.icagile.com/verification-placeholder-acc",
    institutionUrl: "https://www.icagile.com/",
    category: "Agile",
  },
];
